apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hive.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hive.labels" . | indent 4 }}
  annotations:
    # Create the secret before installation, and only then. This saves the secret from regenerating during an upgrade
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  # Generate a random secret if the user doesn't give one. User given password has priority
  dsn: {{ .Values.hive.config.dsn | b64enc | quote }}
