{{- if .Values.service.public.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-public
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hive.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.public.type }}
  ports:
    - port: {{ .Values.service.public.port }}
      targetPort: http-public
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
