{{- if .Values.service.admin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hive.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: http-admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
