hydra:
  autoMigrate: true
  dangerousForceHttp: true
  config:
    dsn: "postgres://ory:ory@postgresql.default.svc.cluster.local/ory?sslmode=disable&max_conn_lifetime=10s"
    secrets:
      system: OG5XbmxXa3dYeGplQXpQanYxeEFuRUFa
maester:
  enabled: false

# deployment:
#  extraVolumes:
#   - name: my-volume
#     secret:
#       secretName: my-secret
#   extraVolumeMounts:
#   - name: my-volume
#     mountPath: /etc/secrets/my-secret
#     readOnly: true

# watcher:
#   enabled: true
#   mountFile: /etc/secrets/my-secret/foo