hydra:
  autoMigrate: true
  dangerousForceHttp: true
  config:
    dsn: "postgres://ory:ory@postgresql.default.svc.cluster.local/ory?sslmode=disable&max_conn_lifetime=10s"
    secrets:
      system: OG5XbmxXa3dYeGplQXpQanYxeEFuRUFa
maester:
  enabled: false