---
keto:
  automigration: 
    enabled: true
  config:
    dsn: "postgres://postgres:ory@postgresql.default.svc.cluster.local/ory?sslmode=disable&max_conn_lifetime=10s"
ingress:
  read:
    enabled: true
  write:
    enabled: true
deployment:
  extraLabels:
    ory.sh/test: keto
  annotations:
    ory.sh/test-annotations: "true"
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
  extraEnv:
    - name: FOO
      value: BAR
job:
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep 10"]
  shareProcessNamespace: true

service:
  metrics:
    enabled: true

serviceMonitor:
  labels:
    release: "prometheus"
  tlsConfig: 
    insecureSkipVerify: true