---
keto:
  autoMigrate: true
  config:
    dsn: "postgres://postgres:ory@postgresql.default.svc.cluster.local/ory?sslmode=disable&max_conn_lifetime=10s"
ingress:
  read:
    enabled: true
  write:
    enabled: true
extraLabels:
  ory.sh/test: keto
deployment:
  annotations:
    ory.sh/test-annotations: "true"
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]

job:
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep 10"]
      
  shareProcessNamespace: true