{{ if not .Values.demo }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oathkeeper.fullname" . }}-config
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "oathkeeper.labels" . | indent 4 }}
data:
  "config.yaml": |
    {{- include "oathkeeper.configmap" . | nindent 4 }}
{{ end }}
