{{- if .Values.httproute.proxy.enabled -}}
{{- $fullName := include "oathkeeper.fullname" . -}}
apiVersion: {{ default "gateway.networking.k8s.io/v1" .Values.httproute.proxy.apiVersion }}
kind: HTTPRoute
metadata:
  name: {{ default (printf "%s-proxy" $fullName) .Values.httproute.proxy.nameOverride }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "oathkeeper.labels" . | nindent 4 }}
    {{- with .Values.httproute.proxy.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httproute.proxy.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.proxy.parentRefs }}
  parentRefs:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  {{- with .Values.httproute.proxy.hostnames }}
  hostnames:
    {{- range . }}
    - {{ tpl . $ | quote }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.httproute.proxy.rules }}
    {{- tpl (toYaml .Values.httproute.proxy.rules) $ | nindent 4 }}
  {{- else }}
    - backendRefs:
        - name: {{ $fullName }}-proxy
          port: {{ default $.Values.service.proxy.port .Values.httproute.proxy.servicePort }}
          {{- if .Values.httproute.proxy.weight }}
          weight: {{ .Values.httproute.proxy.weight }}
          {{- end }}
      {{- if .Values.httproute.proxy.matches }}
      matches:
        {{- tpl (toYaml .Values.httproute.proxy.matches) $ | nindent 8 }}
      {{- else }}
      matches:
        - path:
            type: PathPrefix
            value: /
      {{- end }}
      {{- with .Values.httproute.proxy.filters }}
      filters:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
