{{- if .Values.ingress.proxy.enabled -}}
{{- $fullName := include "oathkeeper.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oathkeeper.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.proxy.defaultBackendService.enabled }}
    ingress.kubernetes.io/rewrite-target: /
  {{- end }}
  {{- with .Values.ingress.proxy.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.proxy.className }}
  {{- if .Values.ingress.proxy.tls }}
  tls:
    {{- range .Values.ingress.proxy.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.proxy.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-proxy
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}-proxy
              servicePort: http
              {{- end }}
          {{- end }}
    {{- end }}
    {{- if .Values.ingress.proxy.defaultBackendService.enabled }}
    - http:
        paths:
        - backend:
            service:
              name: {{ .Values.ingress.proxy.defaultBackendService.name }}
              port:
                name: {{ .Values.ingress.proxy.defaultBackendService.portName }}
          path: /
          pathType: Prefix
    {{- end }}
{{- end }}
