{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oathkeeper.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "oathkeeper.labels" . | indent 4 }}
  annotations:
{{- with .Values.secret.secretAnnotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
data:
{{- if .Values.oathkeeper.mutatorIdTokenJWKs }}
  "{{ .Values.secret.filename }}": {{ default "" .Values.oathkeeper.mutatorIdTokenJWKs | b64enc | quote }}
{{- end}}
{{- end }}
