{{- if .Values.secret.manage }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ empty .Values.secret.name | ternary (include "oathkeeper.fullname" .) (.Values.secret.name) }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "oathkeeper.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.oathkeeper.mutatorIdTokenJWKs }}
  "{{ .Values.secret.filename }}": {{ default "" .Values.oathkeeper.mutatorIdTokenJWKs | b64enc | quote }}
{{- end}}
{{- end }}
