{{- if and .Values.secret.enabled .Values.oathkeeper.mutatorIdTokenJWKs -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oathkeeper.secretname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "oathkeeper.labels" . | indent 4 }}
  annotations: 
    {{- include "oathkeeper.secrets.annotations" . | nindent 4 }}
type: Opaque
data:
  "{{ .Values.secret.filename }}": {{ default "" .Values.oathkeeper.mutatorIdTokenJWKs | b64enc | quote }}
{{- else if and (not .Values.secret.enabled) .Values.oathkeeper.mutatorIdTokenJWKs }}
{{- fail ".Values.secret.enabled must be set to true with .Values.oathkeeper.mutatorIdTokenJWKs" }}
{{- end }}
