{{- if .Values.service.proxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oathkeeper.fullname" . }}-proxy
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/component: proxy
{{ include "oathkeeper.labels" . | indent 4 }}
    {{- with .Values.service.proxy.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.proxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.proxy.type }}
  {{- if eq .Values.service.proxy.type "LoadBalancer" }}
  {{- with .Values.service.proxy.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- if .Values.service.proxy.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.proxy.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.proxy.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.service.proxy.internalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.proxy.port }}
      targetPort: http-proxy
      protocol: TCP
      name: {{ .Values.service.proxy.name }} 
  selector:
    app.kubernetes.io/name: {{ include "oathkeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
