{{- if .Values.service.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oathkeeper.fullname" . }}-api
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/component: api
{{ include "oathkeeper.labels" . | indent 4 }}
    {{- with .Values.service.api.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.api.type }}
  {{- if eq .Values.service.api.type "LoadBalancer" }}
  {{- with .Values.service.api.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  {{- if .Values.service.api.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.api.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.api.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.service.api.internalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http-api
      protocol: TCP
      name: {{ .Values.service.api.name }} 
  selector:
    app.kubernetes.io/name: {{ include "oathkeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
