apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oathkeeper
  name: oathkeeper-api
  namespace: default
spec:
  ports:
  - name: http
    port: 4456
    protocol: TCP
    targetPort: http-api
  selector:
    app.kubernetes.io/name: oathkeeper
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: oathkeeper
  name: oathkeeper-proxy
  namespace: default
spec:
  ports:
    - name: http
      port: 4455
      protocol: TCP
      targetPort: http-proxy
  selector:
    app.kubernetes.io/instance: oathkeeper
    app.kubernetes.io/name: oathkeeper
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: oathkeeper
  name: oathkeeper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oathkeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oathkeeper
    spec:
      containers:
        - command:
            - oathkeeper
            - serve
            - --config
            - /etc/config/config.yaml
          image: oryd/oathkeeper:v0.32.0-beta.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health/alive
              port: http-api
          name: oathkeeper
          ports:
            - containerPort: 4456
              name: http-api
              protocol: TCP
            - containerPort: 4455
              name: http-proxy
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http-api
          volumeMounts:
            - mountPath: /etc/config
              name: oathkeeper-config-volume
              readOnly: true
            - mountPath: /etc/rules
              name: oathkeeper-rules-volume
              readOnly: true
            - mountPath: /etc/secrets
              name: oathkeeper-secrets-volume
              readOnly: true
      volumes:
        - configMap:
            name: oathkeeper-config
          name: oathkeeper-config-volume
        - configMap:
            name: oathkeeper-rules
          name: oathkeeper-rules-volume
        - name: oathkeeper-secrets-volume
          secret:
            secretName: oathkeeper
