---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oathkeeper-maester.fullname" . }}-account
  namespace:  {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "oathkeeper-maester.fullname" . }}-role
rules:
  - apiGroups: ["oathkeeper.ory.sh"]
    resources: ["rules"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
    # TODO, fix controller call from all namespaces to single namespace
    # resourceNames:
    #   - {{ .Values.configMapName | default "ory-oathkeeper-rules" }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "oathkeeper-maester.fullname" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "oathkeeper-maester.fullname" . }}-account # Service account assigned to the controller pod.
    namespace:  {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "oathkeeper-maester.fullname" . }}-role
