apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hydra.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
data:
  "config.yaml": |
  {{- with .Values.hydra.config -}}
    {{- toYaml . | nindent 4 }}
  {{- end -}}

