apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hydra.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "hydra.labels" . | nindent 4 }}
data:
  "hydra.yaml": |
    {{- include "hydra.configmap" . | nindent 4 }}
