apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hydra.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "hydra.labels" . | indent 4 }}
data:
  "config.yaml": |
  {{- $config := set .Values.hydra.config "dsn" "redacted" -}}
  {{- $config := set .Values.hydra.config "secrets" "redacted" -}}
  {{- toYaml $config | nindent 4 }}
