apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keto.fullname" . }}-config
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "keto.labels" . | indent 4 }}
data:
  "keto.yaml": |
    {{- include "keto.configmap" . | nindent 4 }}
