{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keto.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "keto.labels" . | indent 4 }}
type: Opaque
data:
  dsn: {{ include "keto.dsn" . | b64enc | quote }}
{{- end }}
