apiVersion: v1
data:
  dsn: cG9zdGdyZXM6Ly9wb3N0Z3JlczpvcnlAcG9zdGdyZXNxbC5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsL29yeV9rcmF0b3M/c3NsbW9kZT1kaXNhYmxlJm1heF9jb25uX2xpZmV0aW1lPTEwcw==
  secretsCookie: Ik9HNVhibXhYYTNkWWVHcGxRWHBRYW5ZeGVFRnVSVUZhIiwiZm9vIGJhciAxMjMgNDU2IGxvcmVtIiwiZm9vIGJhciAxMjMgNDU2IGxvcmVtIDEiLCJmb28gYmFyIDEyMyA0NTYgbG9yZW0gMiIsImZvbyBiYXIgMTIzIDQ1NiBsb3JlbSAzIg==
  secretsSystem: Ik9HNVhibXhYYTNkWWVHcGxRWHBRYW5ZeGVFRnVSVUZhIiwiZm9vIGJhciAxMjMgNDU2IGxvcmVtIiwiZm9vIGJhciAxMjMgNDU2IGxvcmVtIDEiLCJmb28gYmFyIDEyMyA0NTYgbG9yZW0gMiIsImZvbyBiYXIgMTIzIDQ1NiBsb3JlbSAzIg==
kind: Secret
metadata:
  name: hydra-custom
