---
# singleNamespaceMode: true
priorityClassName: "system-cluster-critical"
deployment:
  annotations:
    ory.sh/deployment_annotation: oathkeeper_maester
  podMetadata:
    labels:
      ory.sh/pod_label: oathkeeper_maester
    annotations:
      ory.sh/pod_annotation: oathkeeper_maester
  serviceAccount:
    annotations:
      ory.sh/pod_annotation: oathkeeper_maester
