# Default values for ory-oathkeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: oryd/oathkeeper
  tag: v0.16.0-beta.4
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

demo: false

service:
  proxy:
    enabled: true
    type: ClusterIP
    port: 4455
  api:
    enabled: true
    type: ClusterIP
    port: 4456

ingress:
  proxy:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: proxy.ory-oathkeeper.local
        paths: ["/"]
    tls: []
    #    hosts:
    #      - ory-oathkeeper.local
    #  - secretName: chart-example-tls
  api:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.ory-oathkeeper.local
        paths: ["/"]
    tls: []
    #    hosts:
    #      - ory-oathkeeper.local
    #  - secretName: chart-example-tls

oathkeeper:
  config:
    serve:
      proxy:
        port: 4455
      api:
        port: 4456

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
