global:
  postgresql:
    auth:
      database: "ory"
      username: "ory"
      password: "ory"
      postgresPassword: "ory"
primary:
  initdb:
    scripts:
      init.sql: |
        CREATE DATABASE ory_kratos;
        CREATE DATABASE ory_keto;
        CREATE DATABASE ory_hydra;
auth:
  database: "ory"
  username: "ory"
  password: "ory"
  postgresPassword: "ory"
image:
  repository: "bitnamilegacy/postgresql"
