apiVersion: v1
appVersion: "v0.0.1"
description: A Helm chart for deployoing ORY Kratos Controller in Kubernetes
name: kratos-maester
version: 0.0.1
keywords:
  - zero-trust
  - full-stack
home: https://www.ory.sh/
sources:
  - https://github.com/ory/kratos
  - https://github.com/ory/k8s
maintainers: # (optional)
  - name: ORY Team
    email: hi@ory.sh
    url: https://www.ory.sh/