---
global:
  podMetadata:
    labels:
      ory.sh/global: "mylabel"
    annotations:
      ory.sh/global: |
        {
          "foo": "bar"
        }
adminService:
  name: hydra-admin.default
deployment:
  extraAnnotations:
    ory.sh/deployment_annotation: hydra-maester
  podMetadata:
    labels:
      ory.sh/pod_label: hydra-maester
    annotations:
      ory.sh/pod_annotation: hydra-maester
  serviceAccount:
    annotations:
      ory.sh/pod_annotation: hydra-maester
  extraVolumes:
    - name: "test-volume"
      emptyDir:
        sizeLimit: 1Mi
  extraVolumeMounts:
    - name: "test-volume"
      mountPath: /test-volume
service:
  metrics:
    enabled: true
    annotations:
      ory.sh/test-annotations: "true"
serviceMonitor:
  labels:
    release: "prometheus"
  tlsConfig:
    insecureSkipVerify: true
