apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kratos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kratos.labels" . | indent 4 }}
data:
  "config.yaml": |
{{ include "kratos.configmap" . | nindent 4 }}