{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kratos.fullname" . }}
  labels:
    {{- include "kratos.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kratos.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.autoscaling.targetMemory }}
  - type: Resource
    resource:
      name: memory
      target:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.autoscaling.targetCPU}}
  - type: Resource
    resource:
      name: cpu
      target:
        {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
