{{- if and .Values.secret.enabled .Values.secret.generate -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kratos.fullname" . }}-secret-generator
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
{{ include "kratos.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
{{ include "kratos.labels" . | indent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kratos.fullname" . }}-secret-generator
      containers:
        - name: kubectl
          image: "{{ .Values.secret.image.repository }}:{{ .Values.secret.image.tag }}"
          imagePullPolicy: {{ include "kratos.imagePullPolicy" . }}
          command:
            - /bin/sh
            - -c
            - |
              set -e
              SECRET_NAME="{{ include "kratos.secretname" . }}"
              if ! kubectl get secret $SECRET_NAME; then
                echo "Creating secret $SECRET_NAME"
                kubectl create secret generic $SECRET_NAME \
                  --from-literal=secretsDefault=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32) \
                  --from-literal=secretsCookie=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32) \
                  --from-literal=secretsCipher=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32) \
                  --from-literal=dsn="$DSN"
              else
                echo "Secret $SECRET_NAME already exists"
              fi
              
              # Always update dsn and smtpConnectionURI if they are provided
              echo "Patching secret $SECRET_NAME with latest non-random values"
              kubectl patch secret $SECRET_NAME -p "{\"data\":{\"dsn\":\"$(echo -n "$DSN" | base64 | tr -d '\n')\"}}"
              if [ -n "$SMTP_CONNECTION_URI" ]; then
                kubectl patch secret $SECRET_NAME -p "{\"data\":{\"smtpConnectionURI\":\"$(echo -n "$SMTP_CONNECTION_URI" | base64 | tr -d '\n')\"}}"
              fi
          env:
            - name: DSN
              value: {{ include "kratos.dsn" . | quote }}
            - name: SMTP_CONNECTION_URI
              value: {{ .Values.kratos.config.courier.smtp.connection_uri | default "" | quote }}
      restartPolicy: OnFailure
{{- end }}
