{{- if .Values.deployment.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kratos.serviceAccountName" . }}
  labels:
    {{- include "kratos.labels" . | nindent 4 }}
  {{- with .Values.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  
{{- if .Values.watcher.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kratos.fullname" . }}-watcher
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list", "patch", "get", "watch"]
    resourceNames:
      - {{ include "kratos.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kratos.fullname" . }}-watcher
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kratos.fullname" . }}-watcher
subjects:
  - kind: ServiceAccount
    name: {{ include "kratos.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
