{{- if .Values.watcher.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kratos.serviceAccountName" . }}-watcher
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "kratos.name" . }}-watcher
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kratos.fullname" . }}-watcher
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
rules:
  - apiGroups: ["apps"]
    resources: 
      - deployments
      - statefulsets
    verbs: 
      - list
      - watch
      - get
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
    resourceNames:
      - {{ include "kratos.fullname" . }}
      - {{ include "kratos.fullname" . }}-courier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kratos.fullname" . }}-watcher
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kratos.fullname" . }}-watcher
subjects:
  - kind: ServiceAccount
    name: {{ include "kratos.fullname" . }}-watcher
    namespace: {{ .Release.Namespace }}
{{- end }}