{{- if .Values.service.admin.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.service.admin.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: admin
{{ include "kratos.labels" . | indent 4 }}
  {{- with .Values.service.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: http-admin
      protocol: TCP
      name: {{ .Values.service.admin.name }}
  selector:
    app.kubernetes.io/name: {{ include "kratos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kratos.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admin
{{ include "kratos.labels" . | indent 4 }}
  {{- with .Values.service.admin.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - path: /metrics/prometheus
    port: {{ .Values.service.admin.name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kratos.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: admin
{{- end -}}
{{- end }}
