{{- if .Values.service.public.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos.fullname" . }}-public
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kratos.labels" . | indent 4 }}
  {{- with .Values.service.public.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.public.type }}
  ports:
    - port: {{ .Values.service.public.port }}
      targetPort: http-public
      protocol: TCP
      name: {{ .Values.service.public.name }}
  selector:
    app.kubernetes.io/name: {{ include "kratos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
