{{- if .Values.service.public.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kratos.fullname" . }}-public
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- with .Values.service.public.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: public
    {{- include "kratos.labels" . | nindent 4 }}
  {{- with .Values.service.public.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.public.type }}
  {{- if eq .Values.service.public.type "LoadBalancer" }}
  {{- with .Values.service.public.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.public.port }}
      targetPort: http-public
      protocol: TCP
      name: {{ .Values.service.public.name }}
      {{- if eq .Values.service.public.type "NodePort" }}
      {{- with .Values.service.public.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "kratos.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
