{{- if .Values.kratos.standaloneCourier }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kratos.fullname" . }}-courier
  labels:
    {{- include "kratos.courier.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  # Due to some limitation in the Kratos persistence layer, this has to be a singleton
  replicas: 1
  serviceName: {{ include "kratos.fullname" . }}-courier
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kratos.courier.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "kratos.courier.labels" . | nindent 8 }}
        {{- with .Values.deployment.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.deployment.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.deployment.extraVolumes }}
        {{- toYaml .Values.deployment.extraVolumes | nindent 8 }}
        {{- end }}
        - name: {{ include "kratos.name" . }}-config-volume
          configMap:
            name: {{ include "kratos.fullname" . }}-config
        {{- $root := . -}}
        {{- range $method, $methodEntry := .Values.kratos.emailTemplates }}
        {{- range $result, $resultEntry := $methodEntry }}
        - name: {{ include "kratos.name" $root }}-template-{{ $method }}-{{ $result }}-volume
          configMap:
            name: {{ include "kratos.fullname" $root }}-template-{{ $method }}-{{ $result }}
        {{- end }}
        {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.enabled }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ default (include "kratos.fullname" . ) .Values.serviceAccount.name }}
      {{- end }}
      initContainers:
        - name: wait-for-automigrate
          image: "groundnuty/k8s-wait-for:v1.4"
          imagePullPolicy: IfNotPresent
          args:
            - job
            - {{ include "kratos.automigrate-job-name" . }}
        {{- if .Values.deployment.extraInitContainers }}
        {{- tpl .Values.deployment.extraInitContainers . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}-courier
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["kratos"]
          args: [
            "courier",
            "watch",
            {{- if .Values.kratos.development }}
            "--dev",
            {{- end}}
            "--config",
            "/etc/config/kratos.yaml"
          ]
          volumeMounts:
            {{- if .Values.deployment.extraVolumeMounts }}
            {{- toYaml .Values.deployment.extraVolumeMounts | nindent 12 }}
            {{- end }}
            - name: {{ include "kratos.name" . }}-config-volume
              mountPath: /etc/config
              readOnly: true
            {{- $root := . -}}
            {{- range $method, $methodEntry := .Values.kratos.emailTemplates }}
            {{- range $result, $resultEntry := $methodEntry }}
            - name: {{ include "kratos.name" $root }}-template-{{ $method }}-{{ $result }}-volume
              mountPath: /conf/courier-templates/{{ $method }}/{{ $result }}
              readOnly: true
            {{- end }}
            {{- end }}
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "kratos.secretname" . }}
                  key: dsn
            - name: SECRETS_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: {{ include "kratos.secretname" . }}
                  key: secretsDefault
            - name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ include "kratos.secretname" . }}
                  key: secretsCookie
            {{- if .Values.kratos.config.courier.smtp.connection_uri }}
            - name: COURIER_SMTP_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "kratos.secretname" . }}
                  key: smtpConnectionURI
            {{- end}}
            {{- if .Values.deployment.tracing.datadog.enabled }}
            - name: TRACING_PROVIDER
              value: datadog
            - name: DD_ENV
              value: {{ .Values.deployment.tracing.datadog.env | default "none" | quote }}
            - name: DD_VERSION
              value: {{ .Values.deployment.tracing.datadog.version | default .Values.image.tag | quote }}
            - name: DD_SERVICE
              value: {{ .Values.deployment.tracing.datadog.service | default "ory/kratos" | quote }}
            {{- if .Values.deployment.tracing.datadog.useHostIP }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- end }}
            {{- end }}
            {{- if .Values.deployment.extraEnv }}
            {{- toYaml .Values.deployment.extraEnv | nindent 12 }}
            {{- end }}
        {{- if .Values.deployment.environmentSecretsName }}
          envFrom:
          - secretRef:
              name: {{ .Values.deployment.environmentSecretsName }}
        {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
