---
global:
  dnsDomain: example.com
  podMetadata:
    labels:
      ory.sh/global: "mylabel"
    annotations:
      ory.sh/global: |
        {
          "foo": "bar"
        }

autoscaling:
  enabled: true
  targetCPU:
    type: Utilization
    averageUtilization: 80
  targetMemory:
    type: Utilization
    averageUtilization: 80
  behavior:
    scaleDown:
      selectPolicy: Disabled

kratos:
  automigration:
    enabled: true
    customCommand:
      - kratos
    customArgs:
      - "migrate"
      - "sql"
      - "-e"
      - "--yes"
      - "--config"
      - "/etc/config/kratos.yaml"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  identitySchemas:
    "identity.default.schema.json": |
      {
         "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
         "$schema": "http://json-schema.org/draft-07/schema#",
         "title": "Person",
         "type": "object",
         "properties": {
            "traits": {
               "type": "object",
               "properties": {
                  "email": {
                     "type": "string",
                     "format": "email",
                     "title": "E-Mail",
                     "ory.sh/kratos": {
                        "credentials": {
                           "password": {
                              "identifier": true
                           }
                        },
                        "recovery": {
                           "via": "email"
                        },
                        "verification": {
                           "via": "email"
                        }
                     }
                  }
               },
               "required": [
                  "email"
               ],
               "additionalProperties": false
            }
         }
      }
  config:
    # ciphers:
    #   algorithm: aes
    selfservice:
      #      default_browser_return_url: http://127.0.0.1:4455/
      default_browser_return_url: "http://{{ .Values.global.dnsDomain }}:4455/"
      methods:
        password:
          enabled: true
    log:
      level: debug
    secrets:
      default:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
        - "OG5XbmxXa3dYeGplQXpQanYxeEFuRUFa"
        - "foo bar 123 456 lorem"
        - "foo bar 123 456 lorem 1"
        - "foo bar 123 456 lorem 2"
        - "foo bar 123 456 lorem 3"
    hashers:
      argon2:
        parallelism: 1
        memory: 128MB
        iterations: 2
        salt_length: 16
        key_length: 16
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
  emailTemplates:
    recovery:
      valid:
        subject: Recover access to your account
        body: |-
          Hi, please recover access to your account by clicking the following link:
          <a href="{{ .RecoveryURL }}">{{ .RecoveryURL }}</a>
        plainBody: |-
          Hi, please recover access to your account by clicking the following link: {{ .RecoveryURL }}
      invalid:
        subject: Account access attempted
        body: |-
          Hi, you (or someone else) entered this email address when trying to recover access to an account.
          However, this email address is not on our database of registered users and therefore the attempt has failed. If this was you, check if you signed up using a different address. If this was not you, please ignore this email.
        plainBody: |-
          Hi, you (or someone else) entered this email address when trying to recover access to an account.
    recovery_code:
      valid:
        subject: Recover access to your account
        body: |-
          Hi, please recover access to your account using following code:
          <h1>{{ .RecoveryCode }}</h1>
        plainBody: |-
          Hi, please recover access to your account using following code: {{ .RecoveryCode }}
      invalid:
        subject: Account access attempted
        body: |-
          Hi, you (or someone else) entered this email address when trying to recover access to an account.
          However, this email address is not on our database of registered users and therefore the attempt has failed. If this was you, check if you signed up using a different address. If this was not you, please ignore this email.
        plainBody: |-
          Hi, you (or someone else) entered this email address when trying to recover access to an account.
    verification:
      valid:
        subject: Please verify your email address
        body: |-
          Hi, please verify your account by clicking the following link:
          <a href="{{ .VerificationURL }}">{{ .VerificationURL }}</a>
        plainBody: |-
          Hi, please verify your account by clicking the following link: {{ .VerificationURL }}
      invalid:
        subject:
        body:
        plainBody:
    verification_code:
      valid:
        subject: Please verify your email address
        body: |-
          Hi, please verify your account by clicking the following link:
          <a href="{{ .VerificationURL }}">{{ .VerificationURL }}</a>
          or using the following code: {{ .VerificationCode }}
        plainBody: |-
          Hi, please verify your account by using the following code: {{ .VerificationCode }}
      invalid:
        subject:
        body:
        plainBody:
ingress:
  admin:
    enabled: true
    annotations:
      my.domain: "{{ .Values.global.dnsDomain }}"
    tls:
      - secretName: chart-example-tls
        hosts:
          - "chart-example.{{ $.Values.global.dnsDomain }}"
    hosts:
      - host: "admin.{{ $.Values.global.dnsDomain }}"
        paths:
          - path: /
            pathType: Prefix
  public:
    enabled: true
    annotations:
      my.domain: "{{ .Values.global.dnsDomain }}"
    tls:
      - secretName: chart-example-tls
        hosts:
          - "public-chart-example.{{ $.Values.global.dnsDomain }}"
    hosts:
      - host: "public.{{ $.Values.global.dnsDomain }}"
        paths:
          - path: /
            pathType: Prefix

pdb:
  enabled: true
  spec:
    maxUnavailable: 25%

deployment:
  extraInitContainers: |
    - name: "hello-world"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "echo hello, world!"]
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
  extraVolumeMounts:
    - mountPath: /testdir
      name: test-volume
  extraVolumes:
    - name: test-volume
      configMap:
        name: cm-sample
  extraArgs:
    - --sqa-opt-out
  labels:
    ory.sh/test: kratos
  podMetadata:
    labels:
      ory.sh/pod_label: kratos
    annotations:
      ory.sh/pod_annotation: kratos
  initContainerSecurityContext:
    capabilities:
      drop:
        - ALL
    podSecurityContext:
      runAsNonRoot: false
  extraEnv:
    - name: FOO
      value: BAR
    - name: DSN
      valueFrom:
        secretKeyRef:
          name: dsn-secret
          key: dsn
    - name: RELEASE_NAME
      value: "{{ .Release.Name }}"
  customLivenessProbe:
    failureThreshold: 5
    exec:
      command:
        - /bin/sh
        - -c
        - |-
          wget -S http://127.0.0.1:4434/admin/health/ready -O -
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  customReadinessProbe:
    failureThreshold: 5
    exec:
      command:
        - /bin/sh
        - -c
        - |-
          wget -S http://127.0.0.1:4434/admin/health/ready -O -
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  priorityClassName: "system-cluster-critical"

  environmentSecretsName: env-secrets

statefulSet:
  extraEnv:
    - name: DSN
      valueFrom:
        secretKeyRef:
          name: dsn-secret
          key: dsn
  podMetadata:
    labels:
      ory.sh/pod_label: kratos_courier
    annotations:
      ory.sh/pod_annotation: kratos_courier
  revisionHistoryLimit: 10
  priorityClassName: "system-cluster-critical"

job:
  extraEnv:
    - name: DSN
      valueFrom:
        secretKeyRef:
          name: dsn-secret
          key: dsn
    - name: LOREM
      value: IPSUM
  extraInitContainers: |
    - name: "hello-world"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "echo hello, world!"]
  extraContainers: |
    - name: "sidecar"
      image: "alpine:latest"
      command: ["/bin/sh"]
      args: ["-c", "sleep 10"]
  shareProcessNamespace: true
  podMetadata:
    labels:
      ory.sh/pod_label: kratos_init
    annotations:
      ory.sh/pod_annotation: kratos_init

watcher:
  enabled: true
  mountFile: "/testdir/sample.txt"
  podMetadata:
    labels:
      ory.sh/pod_label: kratos_watcher
    annotations:
      ory.sh/pod_annotation: kratos_watcher
  securityContext:
    capabilities:
      drop:
        - ALL
  podSecurityContext:
    runAsNonRoot: false

cleanup:
  enabled: true
  securityContext:
    capabilities:
      drop:
        - ALL
  podSecurityContext:
    runAsNonRoot: true

cronjob:
  cleanup:
    labels:
      ory.sh/test: kratos
    annotations:
      ory.sh/test: kratos
    podMetadata:
      labels:
        ory.sh/pod_label: kratos
      annotations:
        ory.sh/pod_annotation: kratos
    podSecurityContext:
      runAsNonRoot: true
    extraEnv:
      - name: DSN
        valueFrom:
          secretKeyRef:
            name: dsn-secret
            key: dsn
    extraContainers: |
      - name: "sidecar"
        image: "alpine:latest"
        command: ["/bin/sh"]
        args: ["-c", "sleep infinity"]
    extraInitContainers: |
      - name: "hello-world"
        image: "alpine:latest"
        command: ["/bin/sh"]
        args: ["-c", "echo hello, world!"]
    automountServiceAccountToken: false
    shareProcessNamespace: true
    serviceAccount:
      create: true
      annotations:
        example.com/sa: "cleanup-cronjob"
      name: ""

serviceMonitor:
  enabled: true
  labels:
    release: "prometheus"
  tlsConfig:
    insecureSkipVerify: true
  relabelings:
    - source_labels: [__address__]
      regex: "([^:]+):.*"
      target_label: instance
      replacement: "$1"
  metricRelabelings:
    - source_labels: [__address__]
      regex: "([^:]+):.*"
      target_label: instance
      replacement: "$1"

test:
  busybox:
    repository: docker.io/library/busybox
    tag: 1.36
