name: Format

on:
  pull_request:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - run: make format
      - name: Indicate formatting issues
        run: git diff HEAD --exit-code --color
